# =============================================================================
# GitHub Actions CI/CD 工作流模板
# =============================================================================
# 完整的 CI/CD 流水线，包含构建、测试、安全扫描、部署
#
# 使用方法：
#   1. 复制此文件到 .github/workflows/ci-cd.yml
#   2. 根据项目需要修改环境变量和步骤
#   3. 配置所需的 GitHub Secrets
# =============================================================================

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production

env:
  # 项目配置（根据实际情况修改）
  PROJECT_NAME: ${{ github.event.repository.name }}
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# 并发控制：同一分支只运行最新的工作流
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ===========================================================================
  # 阶段 1: 代码检查
  # ===========================================================================
  lint:
    name: 代码检查
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: ESLint 检查
        run: npm run lint --if-present

      - name: Prettier 格式检查
        run: npm run format:check --if-present

  # ===========================================================================
  # 阶段 2: 安全扫描
  # ===========================================================================
  security:
    name: 安全扫描
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 依赖漏洞扫描
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: 代码安全扫描 (CodeQL)
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: CodeQL 分析
        uses: github/codeql-action/analyze@v3

      - name: 密钥泄露检测
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  # ===========================================================================
  # 阶段 3: 单元测试
  # ===========================================================================
  test:
    name: 单元测试
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 运行测试
        run: npm test -- --coverage --ci

      - name: 上传覆盖率报告
        uses: codecov/codecov-action@v4
        if: matrix.node-version == 18
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  # ===========================================================================
  # 阶段 4: 构建
  # ===========================================================================
  build:
    name: 构建应用
    runs-on: ubuntu-latest
    needs: [test, security]
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建
        run: npm run build

      - name: 生成版本号
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          SHORT_SHA=${GITHUB_SHA::7}
          echo "version=${VERSION}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ steps.version.outputs.version }}
          path: dist/
          retention-days: 7

  # ===========================================================================
  # 阶段 5: 构建 Docker 镜像
  # ===========================================================================
  docker:
    name: 构建 Docker 镜像
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.meta.outputs.tags }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: build-${{ needs.build.outputs.version }}
          path: dist/

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=

      - name: 构建并推送镜像
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ===========================================================================
  # 阶段 6: 部署到 Staging
  # ===========================================================================
  deploy-staging:
    name: 部署到 Staging
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 部署到 Staging
        run: |
          echo "部署到 Staging 环境"
          echo "镜像: ${{ needs.docker.outputs.image }}"
          # 在此添加实际部署命令
          # 例如：kubectl set image deployment/app app=${{ needs.docker.outputs.image }}

      - name: 健康检查
        run: |
          echo "等待服务启动..."
          sleep 30
          # curl -f https://staging.example.com/health || exit 1

      - name: 通知 Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#deployments'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # ===========================================================================
  # 阶段 7: 部署到 Production
  # ===========================================================================
  deploy-production:
    name: 部署到 Production
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://example.com
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 部署到 Production
        run: |
          echo "部署到 Production 环境"
          echo "镜像: ${{ needs.docker.outputs.image }}"
          # 在此添加实际部署命令

      - name: 健康检查
        run: |
          echo "等待服务启动..."
          sleep 30
          # curl -f https://example.com/health || exit 1

      - name: 创建发布
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true

      - name: 通知 Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#deployments'
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
