# =============================================================================
# Pull Request 验证工作流模板
# =============================================================================
# 在 PR 创建/更新时自动运行验证，确保代码质量
#
# 功能：
#   - 代码检查 (lint)
#   - 单元测试
#   - 构建验证
#   - PR 标签自动添加
#   - 变更检测
# =============================================================================

name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main, develop]

env:
  NODE_VERSION: '18'

# PR 并发控制
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # ===========================================================================
  # 变更检测
  # ===========================================================================
  changes:
    name: 检测变更
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
      tests: ${{ steps.filter.outputs.tests }}
      docs: ${{ steps.filter.outputs.docs }}
      config: ${{ steps.filter.outputs.config }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 检测文件变更
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'lib/**'
            tests:
              - 'tests/**'
              - '**/*.test.ts'
              - '**/*.spec.ts'
            docs:
              - 'docs/**'
              - '*.md'
            config:
              - '*.json'
              - '*.yaml'
              - '*.yml'
              - 'Dockerfile'

  # ===========================================================================
  # 代码质量检查
  # ===========================================================================
  quality:
    name: 代码质量
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.src == 'true'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: ESLint 检查
        run: npm run lint --if-present

      - name: TypeScript 类型检查
        run: npm run typecheck --if-present

      - name: Prettier 格式检查
        run: npm run format:check --if-present

  # ===========================================================================
  # 单元测试
  # ===========================================================================
  test:
    name: 单元测试
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.src == 'true' || needs.changes.outputs.tests == 'true'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 运行测试
        run: npm test -- --coverage --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: ./reports
          JEST_JUNIT_OUTPUT_NAME: junit.xml

      - name: 测试报告
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Jest Tests
          path: reports/junit.xml
          reporter: jest-junit

      - name: 覆盖率评论
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          json-summary-path: ./coverage/coverage-summary.json
          json-final-path: ./coverage/coverage-final.json

  # ===========================================================================
  # 构建验证
  # ===========================================================================
  build:
    name: 构建验证
    runs-on: ubuntu-latest
    needs: [quality, test]
    if: always() && !cancelled()
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建
        run: npm run build

      - name: 检查构建产物
        run: |
          if [ -d "dist" ]; then
            echo "构建成功，产物大小:"
            du -sh dist/
          else
            echo "警告: 没有找到 dist 目录"
          fi

  # ===========================================================================
  # PR 标签管理
  # ===========================================================================
  labeler:
    name: 自动标签
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 自动添加标签
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  # ===========================================================================
  # PR 大小检查
  # ===========================================================================
  pr-size:
    name: PR 大小检查
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 检查 PR 大小
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: 10
          s_label: 'size/S'
          s_max_size: 100
          m_label: 'size/M'
          m_max_size: 500
          l_label: 'size/L'
          l_max_size: 1000
          xl_label: 'size/XL'
          fail_if_xl: false
          message_if_xl: |
            这个 PR 包含大量变更。考虑将其拆分为更小的 PR 以便于审查。

  # ===========================================================================
  # 结果汇总
  # ===========================================================================
  summary:
    name: 验证汇总
    runs-on: ubuntu-latest
    needs: [quality, test, build]
    if: always()
    steps:
      - name: 汇总结果
        run: |
          echo "## PR 验证结果" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| 检查项 | 状态 |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|------|" >> $GITHUB_STEP_SUMMARY
          echo "| 代码质量 | ${{ needs.quality.result == 'success' && '✅' || needs.quality.result == 'skipped' && '⏭️' || '❌' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 单元测试 | ${{ needs.test.result == 'success' && '✅' || needs.test.result == 'skipped' && '⏭️' || '❌' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 构建验证 | ${{ needs.build.result == 'success' && '✅' || needs.build.result == 'skipped' && '⏭️' || '❌' }} |" >> $GITHUB_STEP_SUMMARY

      - name: 检查是否通过
        if: contains(needs.*.result, 'failure')
        run: |
          echo "❌ 部分检查未通过，请查看详细日志"
          exit 1
