name: 持续部署流程
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DEPLOY_ENV: production

jobs:
  # 构建和推送Docker镜像
  build-and-push:
    name: 构建和推送Docker镜像
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Docker元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到容器注册表
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建和推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # 部署到生产环境
  deploy:
    name: 部署到生产环境
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: 部署到Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/${{ github.event.repository.name }} ${{ github.event.repository.name }}=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}

      - name: 验证部署
        run: |
          kubectl rollout status deployment/${{ github.event.repository.name }}
          kubectl get pods