name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
    
    - name: Run unit tests
      run: |
        chmod +x tests/run-tests.sh
        ./tests/run-tests.sh --unit-only --verbose
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/
    
    - name: Run integration tests
      run: |
        ./tests/run-tests.sh --int-only --verbose
    
    - name: Validate scripts
      run: |
        # 验证所有脚本的语法
        find . -name "*.sh" -not -path "./.git/*" -not -path "./node_modules/*" | while read -r script; do
          echo "Validating $script"
          bash -n "$script"
        done